### ISSUE TITLE
Store data in file

### ISSUE THREAD

**Issue by davidep87** [fabioricali/incache#1]
If node process will be restarted we lost all data stored in cache. 
This is not a problem in most of condition but there are few scenarios where this could be a problem, for example if you store information about sessions during a restart you probably get unverified session.
Is it possible to add an option that store data in a file ?

**Comment by fabiorc428** [comment]
This feature was added in version 3.0.0

**Comment by entrptaher** [comment]
@fabioricali what happens when multiple processes access the same persistence file at same time? Will one of the process fail to save the data?

**Comment by fabiorc428** [comment]
@entrptaher I belive that you could get an error like this: EBUSY: resource busy or locked
