### ISSUE TITLE
[ Feature ] Load/Save automatically or manually

### ISSUE THREAD

**Issue by julianxhokaxhiu** [fabioricali/incache#2]
Hi,

I saw that the library exposes only a flag called `save` which defines if we want to save the current memory stack to a file in the disk. This is very useful, although the loading part feels a little bit undocumented and also is not really clear how to know when the memory is ready after load.

Therefore I purpose a little change that will greatly improve the overall development experience with this library. What we need to do are basically two things:

1) Expose two simple flags called `autoload` and `autosave`, which will provide transparency on which of the two ( or both ) actions do we need. An example will be:
```javascript
const storage = new InCache({
  // Provide an autoloading mechanism in the constructor
  autoload: true,
  // Basically is the `save` flag, with a more transparent naming
  autosave: true
})
```

2) Expose two methods, that could also be used internally by the library, that are named `.load()` and `.save()`. These two methods, will obviously take care of loading and saving the internal memory. They must always return a Promise, and always resolve depending on the `auto` flag relatively set. An example would be:
```javascript
const load = () => {
  return new Promise(
    ( resolve, reject ) => {
      if ( opts.autoload ) {
        // load the file from memory and resolve when done, reject if any error occours
      } else
        resolve()
    }
  )
}
```
Same applies for `.save()`

If you have any question feel free to reach me on this issue anytime.

Thank you in advance,
Julian

**Comment by fabiorc428** [comment]
Hi,

you can try the latest version (6.0.0).
Your requests are among the new features.

Regards
