### ISSUE TITLE
Wrong Webpack configuration

### ISSUE THREAD

**Issue by julianxhokaxhiu** [fabioricali/incache#3]
It took me actually a while to figure it out why I was having this issue once running the latest version of this library:
```
Unhandled Rejection at: Promise { <rejected> 'fs.writeFileSync is not a function' } reason: fs.writeFileSync is not a function
```

Once I found out that in your webpack config, you have [this line](https://github.com/fabioricali/incache/blob/master/webpack.config.js#L35) that is very wrong if you build the library using webpack.

As suggested by Webpack itself, please use `target: 'node'` instead.

Thank you in advance :)

---

For whoever has an issue, this is the workaround you can use:

```js
// Generic require way
const incache = require('incache/index')

// Import way
import incache from 'incache/index'
```

**Comment by fabiorc428** [comment]
Fixed
