### ISSUE TITLE
Cannot use without a physical cache file

### ISSUE THREAD

**Issue by robbie-cahill** [fabioricali/incache#4]
I'd like to use this as purely in memory storage, with nothing saved to disk.

I get this error when I don't specify a physical file to store the cache in.
`"ENOENT: no such file or directory, open '.incache'"`

The library really should be able to function without actually specifying a file. When one is not specified, should fall back to memory only usage.

**Comment by fabiorc428** [comment]
you can try to set `autoLoad` to false

**Comment by fabiorc428** [comment]
Hi, 
I have fixed it, 
if you set `filePath` to a falsy value, no error will be thrown.
