### ISSUE TITLE
Share data between node applications

### ISSUE THREAD

**Issue by ghost** [fabioricali/incache#6]
Hey,
I need to share data between parent and child nodes. I'm wondering whether I can use inCache for my purpose. I tried to do it, but unfortunately, the child process is not being able to read the stored object. 

So, does the feature to share objects between processes is implemented or not?

**Comment by fabiorc428** [comment]
Hello,

at the moment it is not expected but it's a good idea.
You could create a socket server with inside InCache or use Redis.

Regards
